[package]
name = "cli_parse"
version = "0.1.0"
authors = ["Nishant Joshi <nishantjo.12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
